# Generated by Django 3.2 on 2021-04-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='release_year',
            field=models.IntegerField(),
        ),
    ]
